### ISSUE TITLE
README unclear instruction

### ISSUE THREAD

**Issue by ecceMatth** [RalphBacon/LGT8F328P-Arduino-Clone-Chip-ATMega328P#6]
EDIT: I'm dumb: the file in question was indeed provided...
Hello,
README.md states :
`3 Replace the boards.txt
In the Hardware -> LGT -> AVR folder delete the boards.txt.
Then copy the boards.txt in this GitHub there in place of the one you just deleted.`
There is no link in the quoted text. What boards.txt file are we supposed to copy?
Thanks.

**Comment by RalphBacon** [comment]
Glad you found it!
